### ISSUE TITLE
README: Perl-compatible regular expression library is required

### ISSUE THREAD

**Issue by h-serizawa** [vertica/ODBC-Loader#3]
To build this UDx, it has to install Perl-compatible regular expression library (pcre, pcre-cpp for RHEL compatible distributions) on the nodes. In addition, Development files for pcre (pcre-devel) is required when building it.

Please review this issue and add this requirements in README if necessary.

**Comment by blackeyepanda** [comment]
In https://github.com/vertica/ODBC-Loader/pull/6 @mfelici has update the README for that
