### ISSUE TITLE
cannot make install, pls help!

### ISSUE THREAD

**Issue by lesteryin** [vertica/ODBC-Loader#4]
make install
# install ODBCLoader
Password:
vsql:ddl/install.sql:2: ROLLBACK 3399:  Failure in UDx RPC call InvokeGetLibraryInfo(): Error calling setupExecContext() in User Defined Object [] at [/data/qb_workspaces/jenkins2/ReleaseBuilds/Hammermill/REL-10_1_1-x_hammermill/build/vertica/OSS/UDxFence/vertica-udx-C++.cpp:218], error code: 0, message: Error happened in dlopen(): [/home/dbadmin/ODBC-Loader-main/build/ODBCLoader.so: undefined symbol: _ZNK7pcrecpp2RE13GlobalReplaceERKNS_11StringPieceEPSs]
vsql:ddl/install.sql:3: ROLLBACK 3861:  Library not found: ODBCLoaderLib
vsql:ddl/install.sql:4: ROLLBACK 3861:  Library not found: ODBCLoaderLib
vsql:ddl/install.sql:7: ROLLBACK 2059:  Source with specified name and parameters does not exist: ODBCSource
vsql:ddl/install.sql:8: ROLLBACK 2059:  Parser with specified name and parameters does not exist: ODBCLoader

**Comment by dingqiangliu** [comment]
c++filt _ZNK7pcrecpp2RE13GlobalReplaceERKNS_11StringPieceEPSs
pcrecpp::RE::GlobalReplace(pcrecpp::StringPiece const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const

Looks like there is compatible issue of the version of libpcrecpp on your machine.

**Comment by lesteryin** [comment]
Here is my libpcrecpp. 
rpm -qa | grep pcre
pcre-utf16-8.42-4.el8.x86_64
pcre-8.42-4.el8.x86_64
pcre-devel-8.42-4.el8.x86_64
pcre2-10.32-2.el8.x86_64
pcre-utf32-8.42-4.el8.x86_64
pcre-cpp-8.42-4.el8.x86_64

Can you provide the right version of libpcrecpp?

**Comment by dingqiangliu** [comment]
Uninstall pcre-devel* and pcre-cpp* packages, and:
```bash 
    # compile & install pcre on every Vertica node
    wget https://downloads.sourceforge.net/project/pcre/pcre/8.45/pcre-8.45.tar.bz2
    tar -xjvf pcre-8.45.tar.bz2
    (cd ./pcre-8.45; ./configure CXXFLAGS='-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0')
    (cd ./pcre-8.45; make install)

    # compile & install ODBC-Loader on just one of Vertica nodes
    git clone https://github.com/vertica/ODBC-Loader
    cd ODBC-Loader
    make install
```

**Comment by h-serizawa** [comment]
@LusienBardhi Did you follow the steps described in https://github.com/vertica/ODBC-Loader#pcre-missing-symbols ?

**Comment by LusienBardhi** [comment]
Yes i follow all step but i give the same error

**Comment by h-serizawa** [comment]
@LusienBardhi Can you check if ODBCLoader.so can refer to libpcrecpp.so.0 file by using "ldd ODBCLoader.so"? Does libpcrecpp.so.0 file exist in the directory defined in LD_LIBRARY_PATH environment variable?

**Comment by LusienBardhi** [comment]
i checked i don't have this environment variable thanks for help.

**Comment by LusienBardhi** [comment]
and i check with command ldd and it refer to libcrecpp.so.0 and i create the environment variable LD_LIBRARY_PATH whit the route of libcrecpp.so.0

**Comment by h-serizawa** [comment]
@LusienBardhi I believe you saw the following error messages. Please check the first line. This line shows the node where the issue occurred. If that is not the node where you are working, please install PCRE library on it. It requires all nodes have to have that library.

vsql:ddl/install.sql:2: ROLLBACK 2175:  An error occurred when loading library file on node **v_trial_node0002**, message:
Failure in UDx RPC call InvokeCheckLibrary(): Error calling setupExecContext() in User Defined Object [] at [/data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/OSS/UDxFence/vertica-udx-C++.cpp:237], error code: 0, message: Error happened in dlopen(): [libodbc.so.2: cannot open shared object file: No such file or directory]
vsql:ddl/install.sql:3: ROLLBACK 3861:  Library not found: ODBCLoaderLib
vsql:ddl/install.sql:4: ROLLBACK 3861:  Library not found: ODBCLoaderLib
vsql:ddl/install.sql:7: ROLLBACK 2059:  Source with specified name and parameters does not exist: ODBCSource
vsql:ddl/install.sql:8: ROLLBACK 2059:  Parser with specified name and parameters does not exist: ODBCLoader

**Comment by LusienBardhi** [comment]
@h-serizawa thanks it worked i installed all.
